const DESAFIOS = [
  {
    dia: 1,
    titulo: 'O Amor é paciente',
    referencia: 'Efésios 4:2',
    versiculo: 'Sejam completamente humildes e dóceis, e sejam pacientes, suportando uns aos outros com amor.',
    desafio: 'Apesar do amor se comunicar de várias formas, as palavras, na maioria das vezes, refletem o estado do nosso coração. Para este dia, decida demonstrar paciência e de modo algum diga algo negativo para o seu cônjuge. Se a tentação surgir, não diga nada. É melhor segurar a língua do que dizer algo de que possa se arrepender depois.',
  },
  {
    dia: 2,
    titulo: 'O Amor é bondoso',
    referencia: 'Efésios 4:32',
    versiculo: 'Sejam bondosos e compassivos uns para com os outros, perdoando-se mutuamente, assim como Deus os perdoou em Cristo.',
    desafio: 'Além de, mais uma vez, não dizer palavras negativas ao seu cônjuge hoje, demonstre bondade com, no mínimo, um gesto inesperado e gentil.',
  },
  {
    dia: 3,
    titulo: 'O Amor não é egoísta',
    referencia: 'Romanos 12:1',
    versiculo: 'Dediquem-se uns aos outros com amor fraternal. Prefiram dar honras aos outros mais do que a si próprios.',
    desafio: 'Aquilo em que você colocar seu tempo, energia e dinheiro, será mais importante para você. É difícil se importar com algo em que você não está investindo. Além de evitar comentários negativos, compre para o seu cônjuge alguma coisa que diga: "eu estava pensando em você hoje".',
  },
  {
    dia: 4,
    titulo: 'O Amor é atencioso',
    referencia: 'Salmos 139:17-18',
    versiculo: 'Como são preciosos para mim os teus pensamentos... Como é grande a soma deles! Se eu os contasse, seriam mais do que os grãos de areia.',
    desafio: 'Faça contato com o seu cônjuge em algum momento durante a agitação do dia. Não faça outra coisa senão perguntar como ele está e se tem algo que você pode fazer por ele.',
  },
  {
    dia: 5,
    titulo: 'O Amor não maltrata',
    referencia: 'Provérbios 27:14',
    versiculo: 'A bênção dada aos gritos cedo de manhã, como maldição é recebida.',
    desafio: 'Peça ao seu cônjuge para lhe dizer três coisas sobre você que o deixam desconfortável e irritado. Faça isso sem atacá-lo e sem justificar seu comportamento. Preocupe-se apenas com a perspectiva dele.',
  },
  {
    dia: 6,
    titulo: 'O Amor não se irrita facilmente',
    referencia: 'Provérbios 16:32',
    versiculo: 'Melhor é o homem paciente do que o guerreiro, e o que governa o seu espírito do que o que toma uma cidade.',
    desafio: 'Escolha hoje para reagir de maneira amorosa, apesar das circunstâncias do seu casamento. Comece fazendo uma lista das áreas em que você precisa separar um tempo para respirar. Então, faça uma lista das motivações negativas e abra mão delas.',
  },
  {
    dia: 7,
    titulo: 'O Amor acredita sempre no melhor',
    referencia: '1 Coríntios 13:7',
    versiculo: '[O amor] tudo crê, tudo espera.',
    desafio: 'Pegue duas folhas de papel. Na primeira, passe alguns minutos escrevendo coisas positivas a respeito do seu cônjuge. Depois, na segunda folha, faça o mesmo com as coisas negativas. Coloque as duas folhas em um lugar secreto para o próximo dia. Em algum ponto durante o dia, escolha um atributo positivo e agradeça ao seu cônjuge por ter essa característica.',
  },
  {
    dia: 8,
    titulo: 'O Amor não arde em ciúmes',
    referencia: 'Cantares de Salomão 8:6',
    versiculo: 'Pois o amor é tão forte quanto é a morte, e o ciúme é tão inflexível quanto é a sepultura. Suas brasas são fogo ardente, são labaredas do Senhor.',
    desafio: 'Decida ser o maior fã do seu cônjuge, e decida rejeitar qualquer pensamento invejoso. Pegue a lista de atributos negativos que você fez ontem e, discretamente, queime-a. Depois, compartilhe com seu cônjuge o quanto você está feliz com o sucesso que ele conquistou recentemente.',
  },
  {
    dia: 9,
    titulo: 'O Amor deixa boas impressões',
    referencia: '1 Pedro 5:14',
    versiculo: 'Saudem uns aos outros com beijo de santo amor.',
    desafio: 'Pense em uma maneira especial de cumprimentar o seu cônjuge hoje. Faça isso com um sorriso e com entusiasmo. Então, decida mudar a maneira como o cumprimenta de modo que reflita o seu amor por ele.',
  },
  {
    dia: 10,
    titulo: 'O Amor é incondicional',
    referencia: 'Romanos 5:8',
    versiculo: 'Mas Deus demonstra o Seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores.',
    desafio: 'Faça algo fora do normal para o seu cônjuge — algo que prove (para você e para ele) que o seu amor é baseado em suas escolhas e em nada mais. Lave o carro. Limpe a cozinha. Compre a sobremesa favorita.',
  },
  {
    dia: 11,
    titulo: 'O Amor valoriza o outro',
    referencia: '1 Pedro 3:7',
    versiculo: 'Igualmente vós, maridos, vivei com elas com entendimento, dando honra à mulher como sendo herdeira convosco da graça da vida.',
    desafio: 'Pense nos últimos dias. Seu cônjuge sabe que você valoriza o casamento? Hoje, encontre um momento para olhar nos olhos dele e dizer sinceramente por que você é grato por tê-lo como parceiro de vida. Seja específico e genuíno.',
  },
  {
    dia: 12,
    titulo: 'O Amor deixa o outro vencer',
    referencia: 'Filipenses 2:4',
    versiculo: 'Não olhe cada um somente para o que é seu, mas cada qual também para o que é dos outros.',
    desafio: 'Demonstre amor através da disposição, escolhendo ceder em uma área de desacordo entre você e seu cônjuge. Diga a ele que você está colocando a preferência dele em primeiro lugar.',
  },
  {
    dia: 13,
    titulo: 'O Amor é justo',
    referencia: 'Marcos 3:25',
    versiculo: 'Se uma casa se dividir contra si mesma, tal casa não poderá subsistir.',
    desafio: 'Converse com o seu cônjuge e estabeleça regras saudáveis de conflito. Se o seu cônjuge não estiver pronto para isso, então escreva os seus limites pessoais para a "briga". Decida colocá-los em prática quando o próximo desentendimento ocorrer.',
  },
  {
    dia: 14,
    titulo: 'O Amor sente prazer',
    referencia: 'Eclesiastes 9:9',
    versiculo: 'Goza a vida com a mulher que amas, todos os dias da tua vida vã.',
    desafio: 'Propositadamente, negligencie uma atividade que normalmente faria para gastar um tempo de qualidade com o seu cônjuge. Faça algo que ele amaria fazer, ou um projeto que gostaria muito de realizar. Apenas estejam juntos.',
  },
  {
    dia: 15,
    titulo: 'O Amor é nobre',
    referencia: '1 Pedro 3:7',
    versiculo: 'Igualmente vós, maridos, vivei com elas com entendimento, dando honra à mulher, como sendo elas herdeiras convosco da graça da vida.',
    desafio: 'Escolha uma maneira de demonstrar honra e respeito ao seu cônjuge que vá além da sua rotina. Pode ser abrir a porta para ela. Pode ser separar as roupas que ele irá vestir. Pode ser a forma como você ouve e fala com ele. Mostre ao seu cônjuge que ele é altamente honrado aos seus olhos.',
  },
  {
    dia: 16,
    titulo: 'O Amor intercede',
    referencia: '3 João 2',
    versiculo: 'Amado, desejo que lhe vá bem em todas as coisas, e que tenhas saúde, assim como bem vai à tua alma.',
    desafio: 'Comece hoje orando pelo coração do seu cônjuge. Ore por três áreas específicas da vida dele onde você deseja que Deus trabalhe. Ore pelo seu casamento.',
  },
  {
    dia: 17,
    titulo: 'O Amor traz intimidade',
    referencia: 'Provérbios 17:9',
    versiculo: 'Aquele que cobre uma ofensa promove amor, mas quem a lança em rosto separa bons amigos.',
    desafio: 'Decida guardar os segredos do seu cônjuge (a menos que seja perigoso para ele ou para você) e ore por ele. Proteja a intimidade do seu casamento.',
  },
  {
    dia: 18,
    titulo: 'O Amor busca entender',
    referencia: 'Provérbios 3:13',
    versiculo: 'Feliz é o homem que acha sabedoria, e o homem que adquire entendimento.',
    desafio: 'Prepare um jantar especial em casa só para vocês dois. Separe este momento para conhecer seu cônjuge melhor, talvez em áreas que vocês raramente conversam. Decida fazer desta uma noite agradável para você e para o seu amor.',
  },
  {
    dia: 19,
    titulo: 'É impossível amar?',
    referencia: '1 João 4:7',
    versiculo: 'Amados, amemo-nos uns aos outros, porque o amor é de Deus; e todo o que ama é nascido de Deus e conhece a Deus.',
    desafio: 'Olhe os desafios dos dias anteriores. Existe algum que parecia impossível para você? Você percebeu que precisa de Deus para mudar seu coração e lhe dar capacidade para amar? Peça a Ele para mostrar onde você precisa da intervenção Dele, e peça força e graça para cumprir o seu destino eterno.',
  },
  {
    dia: 20,
    titulo: 'Jesus Cristo é amor',
    referencia: 'Romanos 5:6',
    versiculo: 'Pois, quando ainda éramos fracos, Cristo morreu a seu tempo pelos ímpios.',
    desafio: 'Desafio você a conhecer a Deus pela palavra. Desafio você a crer em Jesus como seu salvador. Ore: "Senhor Jesus, sou pecador, mas o Senhor mostrou o Teu amor por mim morrendo para perdoar os meus pecados, e o Senhor provou o Teu poder de me salvar da morte através da ressurreição. Senhor, mude o meu coração, e salve-me pela Tua graça."',
  },
  {
    dia: 21,
    titulo: 'O Amor é saciado em Deus',
    referencia: 'Isaías 58:11',
    versiculo: 'O Senhor lhe guiará constantemente; satisfará os seus desejos.',
    desafio: 'Separe hoje um tempo para orar e ler a Bíblia. Tente ler um capítulo de Provérbios a cada dia (são trinta e um — um suprimento para o mês todo), ou leia um capítulo dos evangelhos (Mateus, Marcos, Lucas ou João). Mergulhe no amor e nas promessas que Deus tem para você.',
  },
  {
    dia: 22,
    titulo: 'O Amor é fiel',
    referencia: 'Oséias 2:20',
    versiculo: 'E desposar-te-ei comigo em fidelidade, e conhecerás ao Senhor.',
    desafio: 'Amar é uma escolha. Não um sentimento. É uma ação inicial, não uma ação automática. Hoje, escolha estar comprometido a amar o seu cônjuge de forma incondicional. Reafirme esse compromisso olhando nos olhos dele e dizendo: "Eu escolho amar você."',
  },
  {
    dia: 23,
    titulo: 'O Amor sempre protege',
    referencia: '1 Coríntios 13:7',
    versiculo: '[O amor] tudo sofre, tudo crê, tudo espera, tudo suporta.',
    desafio: 'Remova qualquer coisa que esteja atrapalhando seu relacionamento — qualquer vício ou influência que esteja se infiltrando em seu amor e afastando seu coração do seu cônjuge. Identifique essas ameaças e tome uma atitude concreta para eliminá-las.',
  },
  {
    dia: 24,
    titulo: 'Amor vs. cobiça',
    referencia: '1 João 2:17',
    versiculo: 'O mundo e a sua cobiça passam, mas aquele que faz a vontade de Deus permanece para sempre.',
    desafio: 'Acabe com a cobiça agora. Identifique todo objeto dela em sua vida e remova-o. Rejeite todas as mentiras em que você acreditava ter prazer. A cobiça deve ser destruída e exterminada — hoje — e substituída pelas promessas de Deus e por um coração cheio do Seu perfeito amor.',
  },
  {
    dia: 25,
    titulo: 'O Amor perdoa',
    referencia: '2 Coríntios 2:10',
    versiculo: 'O que eu também perdoei, se é que alguma coisa tenho perdoado, por causa de vós o fiz na presença de Cristo.',
    desafio: 'Seja o que for que você ainda não perdoou em seu cônjuge, perdoe hoje. Esqueça. Assim como pedimos a Deus para "perdoar as nossas dívidas" a cada dia, devemos pedir a Deus para ajudar-nos a "perdoar os nossos devedores" a cada dia também. Diga de coração: "Eu escolho perdoar."',
  },
  {
    dia: 26,
    titulo: 'O Amor é responsável',
    referencia: 'Romanos 2:1',
    versiculo: 'Quando julgas, te condenas a ti mesmo naquilo em que julgas a outro; pois tu que julgas, praticas o mesmo.',
    desafio: 'Separe um tempo para orar pelas áreas onde você tem errado. Peça o perdão de Deus, então, humilhe-se a ponto de admiti-los ao seu cônjuge. Faça isso sinceramente e verdadeiramente. Peça perdão ao seu cônjuge também. Mesmo se ele responder com uma crítica, aceite-a como um conselho.',
  },
  {
    dia: 27,
    titulo: 'O Amor encoraja',
    referencia: 'Salmos 25:20',
    versiculo: 'Guarda a minha alma, e livra-me; não seja eu envergonhado, porque em Ti me refugio.',
    desafio: 'Elimine do seu lar o veneno das expectativas erradas. Pense em uma área onde seu cônjuge tenha dito que você está esperando muito, e diga a ele que você está arrependido por ter exigido tanto. Prometa que vai mudar essa postura.',
  },
  {
    dia: 28,
    titulo: 'O Amor serve',
    referencia: 'Marcos 10:45',
    versiculo: 'Pois o Filho do Homem não veio para ser servido, mas para servir e dar a Sua vida em resgate de muitos.',
    desafio: 'Descubra uma necessidade que seu cônjuge tem e atenda a ela hoje, sem ser pedido e sem esperar nada em troca. Pode ser algo pequeno — uma tarefa que ele odeia fazer, a refeição favorita preparada com carinho, ou simplesmente reservar tempo para ouvir como foi o dia dele.',
  },
  {
    dia: 29,
    titulo: 'A motivação do Amor',
    referencia: 'Efésios 6:7',
    versiculo: 'Servindo de boa vontade como ao Senhor, e não como aos homens.',
    desafio: 'Antes de ver seu cônjuge hoje, ore por ele e por suas necessidades. Diga "eu te amo" — seja fácil para você ou não. Então expresse amor de maneira sensível. Volte a Deus em oração mais uma vez, agradecendo a ele por ter lhe dado o privilégio de amar essa pessoa tão especial — incondicionalmente.',
  },
  {
    dia: 30,
    titulo: 'O Amor traz unidade',
    referencia: 'João 17:11',
    versiculo: 'Pai santo, guarda-os no Teu nome, o qual me deste, para que eles sejam um, assim como nós.',
    desafio: 'Separe uma área que cause divisão em seu casamento e olhe para ela hoje como uma oportunidade única de orar. Peça a Deus para revelar o que há no seu coração que está ameaçando sua unidade. Ore para que Deus faça o mesmo com ele. E se for apropriado, discutam abertamente esse problema, buscando de Deus a unidade.',
  },
  {
    dia: 31,
    titulo: 'O Amor e o casamento',
    referencia: 'Gênesis 2:24',
    versiculo: 'Portanto deixará o homem a seu pai e a sua mãe, e unir-se-á à sua mulher, e serão uma só carne.',
    desafio: 'Existe algum "rompimento" que você ainda não teve coragem de realizar? Confesse-o ao seu cônjuge hoje, e decida agir corretamente. A unidade do seu casamento depende disso. Siga a unidade com o compromisso com seu cônjuge e com Deus de fazer do seu casamento o relacionamento humano mais importante da sua vida.',
  },
  {
    dia: 32,
    titulo: 'O Amor satisfaz',
    referencia: '1 Coríntios 7:3',
    versiculo: 'O marido deve cumprir os seus deveres conjugais para com a sua mulher, e da mesma forma a mulher para com o seu marido.',
    desafio: 'Converse com seu cônjuge sobre as necessidades de intimidade de vocês. Demonstre afeto e atenção genuína. Faça isso de maneira que honre o que seu cônjuge lhe disse a respeito das necessidades dele. Peça a Deus para que esse momento seja agradável para os dois e para que também seja um caminho para uma intimidade cada vez maior.',
  },
  {
    dia: 33,
    titulo: 'O Amor completa um ao outro',
    referencia: 'Eclesiastes 4:9-10',
    versiculo: 'Melhor é serem dois do que um, porque têm melhor paga do seu trabalho. Porque se um cair, o outro levantará o seu companheiro.',
    desafio: 'Reflita sobre como você e seu cônjuge se complementam. Quais são as forças dele que cobrem as suas fraquezas? Quais são as suas que cobrem as dele? Agradeça a Deus por essa complementaridade e diga ao seu cônjuge especificamente como a vida de você é mais completa por causa dele.',
  },
  {
    dia: 34,
    titulo: 'O Amor se alegra na verdade',
    referencia: '1 Coríntios 13:6',
    versiculo: '[O amor] não se regozija com a injustiça, mas se regozija com a verdade.',
    desafio: 'Encontre um exemplo específico e recente de quando seu cônjuge demonstrou caráter cristão de forma notável. Elogie-o verbalmente por isso em algum momento do dia.',
  },
  {
    dia: 35,
    titulo: 'O Amor presta contas',
    referencia: 'Provérbios 15:22',
    versiculo: 'Os planos fracassam por falta de conselho, mas são bem-sucedidos quando há muitos conselheiros.',
    desafio: 'Busque um conselheiro para casais — alguém que seja um cristão firme e que será honesto e amoroso. Se você sente que o aconselhamento é necessário, então dê o primeiro passo para marcar o primeiro encontro. Durante esse processo, peça a Deus para direcionar suas decisões e discernimento.',
  },
  {
    dia: 36,
    titulo: 'O Amor é a palavra de Deus',
    referencia: 'Salmos 119:105',
    versiculo: 'Lâmpada para os meus pés é a Tua palavra, e luz para o meu caminho.',
    desafio: 'Tenha o compromisso de ler a Bíblia todos os dias. Encontre um livro devocional ou outra fonte que lhe servirá como guia. Se seu cônjuge está aberto a isto, veja se ele se comprometerá a ler a Bíblia diariamente com você. Inicie submetendo cada área da sua vida à direção da Palavra de Deus.',
  },
  {
    dia: 37,
    titulo: 'O Amor concorda em oração',
    referencia: 'Mateus 18:19',
    versiculo: '"Se dois de vocês concordarem na terra em qualquer assunto sobre o qual pedirem, isso lhes será feito por Meu Pai que está nos céus."',
    desafio: 'Pergunte ao seu cônjuge se vocês podem começar a orar juntos. Conversem sobre a melhor hora para fazer isso — seja pela manhã, na hora do almoço ou antes de dormir. Utilize este tempo para colocar suas preocupações, discórdias e necessidades diante do Senhor. Mesmo se o seu cônjuge se recusar, decida ter esse tempo de oração diariamente ainda que sozinho.',
  },
  {
    dia: 38,
    titulo: 'O Amor realiza sonhos',
    referencia: 'Salmos 37:4',
    versiculo: 'Deleite-se no Senhor, e Ele atenderá aos desejos do seu coração.',
    desafio: 'Pergunte a si mesmo o que o seu cônjuge iria querer se fosse possível de obter. Leve isso em oração e comece a mapear um plano para ajudá-lo a realizar esse sonho. Pode ser um projeto, uma viagem, um objetivo de vida. Demonstre que você se importa com o que ele sonha.',
  },
  {
    dia: 39,
    titulo: 'O Amor persevera',
    referencia: '1 Coríntios 13:8',
    versiculo: 'O amor nunca falha.',
    desafio: 'Olhe para trás nos 38 dias que você percorreu. O que mudou em você? O que mudou no seu casamento? Escreva isso hoje — seja no campo de notas aqui, seja em um papel. Compartilhe com seu cônjuge como este desafio transformou a sua forma de amar.',
  },
  {
    dia: 40,
    titulo: 'O Amor é uma aliança',
    referencia: 'Rute 1:16',
    versiculo: 'Porque aonde quer que tu fores, irei eu; e onde quer que pousares, ali pousarei eu; o teu povo será o meu povo, o teu Deus será o meu Deus.',
    desafio: 'Escreva novas promessas assim como você fez no dia do seu casamento. Guarde-as em algum lugar da sua casa. Talvez, se for apropriado, você possa renovar essas promessas formalmente diante de um ministro e com a família presente. Faça dessas promessas um testamento vivo do valor do casamento aos olhos de Deus e da grande honra de ser um com seu cônjuge.',
  },
]

export default DESAFIOS
